Rocky - Copy/Models/ApplicationType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Rocky.Models {
    public class ApplicationType {
        [Key]
        public int Id { get; set; }

        public string Name { get; set; }
    }
}

Rocky - Copy/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Rocky.Models {

    public class Category {

        [Key]
        public int Id { get; set; }

        [Required]
        public string Name { get; set; }

        [DisplayName("Display Order")]
        [Required]
        [Range(1, 20, ErrorMessage = "0< x < 20")]
        public int DisplayOrder { get; set; }

        public string Note { get; set; }
    }
}

Rocky - Copy/Models/ErrorViewModel.cs
using System;

namespace Rocky.Models {
    public class ErrorViewModel {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Rocky - Copy/Controllers/ApplicationTypeController.cs
using Microsoft.AspNetCore.Mvc;
using Rocky.Data;
using Rocky.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rocky.Controllers {

    public class ApplicationTypeController : Controller {
        private readonly ApplicationDbContext _db;

        public ApplicationTypeController(ApplicationDbContext db) {
            _db = db;
        }

        public IActionResult Index() {
            IEnumerable<ApplicationType> objlist = _db.ApplicationType;
            return View(objlist);
        }

        //GET-Create
        public IActionResult Create() {
            return View();
        }

        //Post- Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ApplicationType obj) {
            if(ModelState.IsValid) {
                _db.ApplicationType.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //get-edit
        public IActionResult Edit(int? id) {
            if(id == null || id == 0) {
                return NotFound();
            }
            var obj = _db.ApplicationType.Find(id);
            if(obj == null) {
                return NotFound();
            }

            return View(obj);
        }

        //Post- Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ApplicationType obj) {
            if(ModelState.IsValid) {
                _db.ApplicationType.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //get-delete
        public IActionResult Delete(int? id) {
            if(id == null || id == 0) {
                return NotFound();
            }
            var obj = _db.ApplicationType.Find(id);
            if(obj == null) {
                return NotFound();
            }

            return View(obj);
        }

        //Post- delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id) {
            var obj = _db.ApplicationType.Find(id);
            if(obj == null)
                return NotFound();

            _db.ApplicationType.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Rocky - Copy/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Rocky.Data;
using Rocky.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Rocky.Controllers {

    public class CategoryController : Controller {
        private readonly ApplicationDbContext _db;

        public CategoryController(ApplicationDbContext db) {
            _db = db;
        }

        public IActionResult Index() {
            IEnumerable<Category> objlist = _db.Category;
            return View(objlist);
        }

        //GET-Create
        public IActionResult Create() {
            return View();
        }

        //Post- Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Category obj) {
            if(ModelState.IsValid) {
                _db.Category.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //get-edit
        public IActionResult Edit(int? id) {
            if(id == null || id == 0) {
                return NotFound();
            }
            var obj = _db.Category.Find(id);
            if(obj == null) {
                return NotFound();
            }

            return View(obj);
        }

        //Post- Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Category obj) {
            if(ModelState.IsValid) {
                _db.Category.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //get-delete
        public IActionResult Delete(int? id) {
            if(id == null || id == 0) {
                return NotFound();
            }
            var obj = _db.Category.Find(id);
            if(obj == null) {
                return NotFound();
            }

            return View(obj);
        }

        //Post- delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id) {
            var obj = _db.Category.Find(id);
            if(obj == null)
                return NotFound();

            _db.Category.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Rocky - Copy/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Rocky.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Rocky.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rocky - Copy/Views/ApplicationType/Create.cshtml
@model Rocky.Models.ApplicationType

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3"> Add Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">@*keep empty*@</div>
        </div>
    </div>
</form>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky - Copy/Views/ApplicationType/Delete.cshtml
@model Rocky.Models.ApplicationType

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3"> Delete Category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">@*keep empty*@</div>
        </div>
    </div>
</form>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky - Copy/Views/ApplicationType/Edit.cshtml
@model Rocky.Models.ApplicationType

<form method="post" asp-action="Edit">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">  Edit Application Type</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">@*keep empty*@</div>
        </div>
    </div>
</form>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky - Copy/Views/ApplicationType/Index.cshtml
@model IEnumerable<Rocky.Models.ApplicationType>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Application List</h2>
        </div>
        <div class="col-6">
            <a asp-controller="ApplicationType" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> Create New Application
            </a>
        </div>
    </div>
    <br /><br />
    @if(Model.Count() > 0) {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Application Name
                    </th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model) {
                    <tr>
                        <td width="80%">@item.Name</td>

                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="ApplicationType" asp-route-Id="@item.Id" asp-action="Edit" class="btn btn-outline-primary mx-1">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a asp-controller="ApplicationType" asp-route-Id="@item.Id" asp-action="Delete" class="btn btn-danger mx-1">
                                    <i class="far fa-trash-alt"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    } else {
        <p>No ApplicationType in here</p>
    }
</div>

Rocky - Copy/Views/Category/Create.cshtml
@model Rocky.Models.Category

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3"> Add Category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" class="form-control" />
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Note"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Note" class="form-control" />
                        <span asp-validation-for="Note" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">@*keep empty*@</div>
        </div>
    </div>
</form>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky - Copy/Views/Category/Delete.cshtml
@model Rocky.Models.Category

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3"> Delete Category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Note"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Note" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-100" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i>Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">@*keep empty*@</div>
        </div>
    </div>
</form>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky - Copy/Views/Category/Edit.cshtml
@model Rocky.Models.Category

<form method="post" asp-action="Edit">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group row">
            <h2 class="text-info pl-3">  Edit Category</h2>
        </div>
        <div class="row">
            <div class="col-8">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="DisplayOrder"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="DisplayOrder" class="form-control" />
                        <span asp-validation-for="DisplayOrder" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="Note"></label>
                    </div>
                    <div class="col-8">
                        <input asp-for="Note" class="form-control" />
                        <span asp-validation-for="Note" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-4 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-100" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-100"><i class="fas fa-sign-out-alt"></i> Back</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">@*keep empty*@</div>
        </div>
    </div>
</form>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rocky - Copy/Views/Category/Index.cshtml
@model IEnumerable<Rocky.Models.Category>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary"> Category List</h2>
        </div>
        <div class="col-6">
            <a asp-controller="Category" asp-action="Create" class="btn btn-primary">
                <i class="fas fa-plus"></i> Create New Category
            </a>
        </div>
    </div>
    <br /><br />
    @if(Model.Count() > 0) {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Category Name
                    </th>
                    <th>
                        Display Order
                    </th>
                    <th>
                        Note
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach(var item in Model) {
                    <tr>
                        <td width="50%">@item.Name</td>
                        <td width="10%"> @item.DisplayOrder</td>
                        <td width="40%">@item.Note</td>
                        <td class="text-center">
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Category" asp-route-Id="@item.Id" asp-action="Edit" class="btn btn-outline-primary mx-1">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <a asp-controller="Category" asp-route-Id="@item.Id" asp-action="Delete" class="btn btn-danger mx-1">
                                    <i class="far fa-trash-alt"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    } else {
        <p>No category in here</p>
    }
</div>

Rocky - Copy/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Welcome</title>
    <link rel="icon" href="./images/Favicon.png" sizes="32x32" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="./js/common.js"></script>
    <script src="./js/config.js"></script>
    <script src="./js/test.js"></script>
</head>

<style>
    * {
        margin: 0;
        padding: 0;
        text-align: center;
    }

    body {
        background-size: 100% 100%;
        background-attachment: fixed;
        color: #F5F4F6;
        font-size: 13px;
        font-weight: bold;
        overflow: hidden;
        width: 1300px;
        height: 100px;
    }

    audio {
        position: absolute;
        right: 0;
        opacity: 0.1;
        transition: all 1s;
    }

        audio:hover {
            opacity: 1;
        }

    .current {
        color: brown;
    }

    video {
        z-index: -1;
        /* object-fit: fill; */
        position: fixed;
        /* right: 0px;
        bottom: 0px; */
        min-width: 100%;
        min-height: 100%;
        /* height: auto;
        width: auto; */
    }

    .main-content {
        position: absolute;
        top: 50%;
        left: 50%;
    }

        .main-content .year {
            position: relative;
            top: -13px;
            left: -38px;
            text-align: center
        }

            .main-content .year span {
                position: absolute;
                width: 80px;
            }

        .main-content .month {
            position: relative;
            top: -13px;
            left: 40px;
        }

    .month span {
        position: absolute;
        width: 60px;
    }

    .main-content .day {
        position: relative;
        top: -13px;
        left: 85px;
    }

    .day span {
        position: absolute;
        width: 65px;
    }

    .main-content .week {
        position: relative;
        top: -13px;
        left: 145px;
    }

    .week span {
        position: absolute;
        width: 65px;
    }

    .main-content .shichen {
        position: relative;
        top: -13px;
        left: 200px;
    }

    .shichen span {
        position: absolute;
        width: 125px;
    }

    .main-content .hour {
        position: relative;
        top: -13px;
        left: 240px;
    }

    .hour span {
        position: absolute;
        width: 60px;
    }

    .main-content .minute {
        position: relative;
        top: -13px;
        left: 300px;
    }

    .minute span {
        position: absolute;
        width: 60px;
    }

    .main-content .second {
        position: relative;
        top: -13px;
        left: 370px;
    }

    .second span {
        position: absolute;
        width: 60px;
    }
</style>

<body>
    <div class="main-content">
        <div class="year">  </div>
        <div class="month"></div>
        <div class="day"></div>
        <div class="week"></div>
        <div class="shichen"></div>
        <div class="hour"></div>
        <div class="minute"></div>
        <div class="second"></div>
    </div>
    <!-- <footer>
        Give your feedback <a href="https://www.facebook.com/phuctoanz">here</a>
    </footer>-->

</body>
</html>

Rocky - Copy/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rocky</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/bootstrap-lumen.css" type="text/css" />*@
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fontawesome-free-5.15.1-web/css/all.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MySecondWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="ApplicationType" asp-action="Index">ApplicationType</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Account" asp-action="Index">Account</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <hr />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ToanDang - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>